[2024-05-03T15:07:42.238+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: covid_analytics_dag.invoke_lambda manual__2024-05-03T15:07:38.698334+00:00 [queued]>
[2024-05-03T15:07:42.267+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: covid_analytics_dag.invoke_lambda manual__2024-05-03T15:07:38.698334+00:00 [queued]>
[2024-05-03T15:07:42.269+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-05-03T15:07:42.270+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2024-05-03T15:07:42.271+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-05-03T15:07:42.288+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): invoke_lambda> on 2024-05-03 15:07:38.698334+00:00
[2024-05-03T15:07:42.300+0000] {standard_task_runner.py:55} INFO - Started process 388 to run task
[2024-05-03T15:07:42.311+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'covid_analytics_dag', 'invoke_lambda', 'manual__2024-05-03T15:07:38.698334+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/covid_analytics.py', '--cfg-path', '/tmp/tmpftbf639j']
[2024-05-03T15:07:42.326+0000] {standard_task_runner.py:83} INFO - Job 63: Subtask invoke_lambda
[2024-05-03T15:07:42.466+0000] {task_command.py:376} INFO - Running <TaskInstance: covid_analytics_dag.invoke_lambda manual__2024-05-03T15:07:38.698334+00:00 [running]> on host 51fa64552e65
[2024-05-03T15:07:42.654+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Diego Munera
AIRFLOW_CTX_DAG_ID=covid_analytics_dag
AIRFLOW_CTX_TASK_ID=invoke_lambda
AIRFLOW_CTX_EXECUTION_DATE=2024-05-03T15:07:38.698334+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-03T15:07:38.698334+00:00
[2024-05-03T15:07:42.681+0000] {credentials.py:1180} INFO - Found credentials in environment variables.
[2024-05-03T15:07:53.333+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-05-03T15:07:53.378+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=covid_analytics_dag, task_id=invoke_lambda, execution_date=20240503T150738, start_date=20240503T150742, end_date=20240503T150753
[2024-05-03T15:07:53.528+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-05-03T15:07:53.553+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
