[2024-05-02T22:44:10.205+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: covid_analytics_dag.invoke_lambda manual__2024-05-02T22:44:06.633328+00:00 [queued]>
[2024-05-02T22:44:10.218+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: covid_analytics_dag.invoke_lambda manual__2024-05-02T22:44:06.633328+00:00 [queued]>
[2024-05-02T22:44:10.219+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-05-02T22:44:10.221+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2024-05-02T22:44:10.221+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-05-02T22:44:10.246+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): invoke_lambda> on 2024-05-02 22:44:06.633328+00:00
[2024-05-02T22:44:10.268+0000] {standard_task_runner.py:55} INFO - Started process 360 to run task
[2024-05-02T22:44:10.278+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'covid_analytics_dag', 'invoke_lambda', 'manual__2024-05-02T22:44:06.633328+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/covid_analytics.py', '--cfg-path', '/tmp/tmpn4yl00zz']
[2024-05-02T22:44:10.282+0000] {standard_task_runner.py:83} INFO - Job 52: Subtask invoke_lambda
[2024-05-02T22:44:10.408+0000] {task_command.py:376} INFO - Running <TaskInstance: covid_analytics_dag.invoke_lambda manual__2024-05-02T22:44:06.633328+00:00 [running]> on host c3fc1e142c14
[2024-05-02T22:44:10.527+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Diego Munera
AIRFLOW_CTX_DAG_ID=covid_analytics_dag
AIRFLOW_CTX_TASK_ID=invoke_lambda
AIRFLOW_CTX_EXECUTION_DATE=2024-05-02T22:44:06.633328+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-02T22:44:06.633328+00:00
[2024-05-02T22:44:10.572+0000] {credentials.py:1180} INFO - Found credentials in environment variables.
[2024-05-02T22:44:22.679+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-05-02T22:44:22.721+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=covid_analytics_dag, task_id=invoke_lambda, execution_date=20240502T224406, start_date=20240502T224410, end_date=20240502T224422
[2024-05-02T22:44:22.843+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-05-02T22:44:22.878+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
